name: maven

on:
  push:
    branches: [ "main","development","#deployuat" ]
  pull_request:
    branches: [ "main","development" ]

jobs:

  infra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Iniciando os testes
      run: mvn test
      
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build with Maven
      run: mvn package
